### ISSUE TITLE
Priority is assigned to all jobs of the same name in different folders

### ISSUE THREAD

**Issue by imakowski** [jenkinsci/priority-sorter-plugin#22]
I have view with different branches of the same version of product.

I've installed plugin first time. I have advanced configuration with default values (Absolute 3, 5, priorities can be defined only by administrators)

In Job Priorities i defined 1 group with idea that I want to prioritize jobs that will be triggered by user with priority 1 + relation so in my context Upstream jobs.

Priorities are assigned but to all jobs of the same name in different folders example
* Folder1
    * A - gets priority 1 after trigger by user
* Folder2
    * A - gets priority 1 (is not triggered by the user)

I've checked priorities using Priority Column

**Comment by emsa23** [comment]
@imakowski just to check are you using *3.0-beta-1*?

**Comment by imakowski** [comment]
I'm using 2,12. here is my configuration http://snag.gy/b1TfY.jpg

**Comment by emsa23** [comment]
Please first read the information on the [wiki] (https://wiki.jenkins-ci.org/display/JENKINS/Priority+Sorter+Plugin)

Turn on logging as described in the troubleshooting section, that should tell you why the jobs gets the priority it gets.

If you find a behavior that you think is the result of a bug open an issue for [PropioritySorter on Jenkins jira] (http://issues.jenkins-ci.org/secure/IssueNavigator.jspa?mode=hide&reset=true&jqlQuery=project+%3D+JENKINS+AND+status+in+%28Open%2C+%22In+Progress%22%2C+Reopened%29+AND+component+%3D+%27PrioritySorter-plugin%27)

Providing relevant information, including logs as above, makes in easier to track down the bug. 

For beta testing of the 3.0 releases use the github issue tracker.

Thank you.

**Comment by imakowski** [comment]
I've read the wiki before configuration. Can you just tell me if this configuration is correct for what I've described above?

**Comment by emsa23** [comment]
I'm not 100% sure what you try to do but the rules are in any case not additive.

Meaning that:
 * Jobs triggered by user will get prio 1
 * Jobs triggered by upstream will get the same priority as the the upstream Job
 * All other Jobs will get the default priority

Also note that 2.x is not aware of Folders if you want to work directly on Folders please try 3.0-beta-1

In any case - if a Job gets a Priority that you din't expect it to get please turn on logging to get some more information.

Thanks

**Comment by imakowski** [comment]
Thank you
